/**
 * Format content as HTML similar to OpenManus travel handbook
 */
export function formatAsHTML(
  content: string,
  title: string = 'Output'
): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 20px;
        }

        .container {
            max-width: 900px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 10px 40px rgba(0,0,0,0.2);
        }

        h1 {
            color: #667eea;
            font-size: 2.5rem;
            margin-bottom: 20px;
            border-bottom: 3px solid #667eea;
            padding-bottom: 15px;
        }

        h2 {
            color: #764ba2;
            font-size: 1.8rem;
            margin-top: 30px;
            margin-bottom: 15px;
        }

        h3 {
            color: #667eea;
            font-size: 1.4rem;
            margin-top: 20px;
            margin-bottom: 10px;
        }

        p {
            margin-bottom: 15px;
            text-align: justify;
        }

        ul, ol {
            margin-left: 25px;
            margin-bottom: 15px;
        }

        li {
            margin-bottom: 8px;
        }

        strong {
            color: #764ba2;
        }

        a {
            color: #667eea;
            text-decoration: none;
            border-bottom: 1px dotted #667eea;
        }

        a:hover {
            color: #764ba2;
            border-bottom: 1px solid #764ba2;
        }

        .highlight {
            background: linear-gradient(120deg, #f8f0ff 0%, #e8d6ff 100%);
            padding: 20px;
            border-left: 4px solid #667eea;
            margin: 20px 0;
            border-radius: 6px;
        }

        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #eee;
            text-align: center;
            color: #999;
            font-size: 0.9rem;
        }

        @media print {
            body {
                background: white;
                padding: 0;
            }

            .container {
                box-shadow: none;
                padding: 20px;
            }
        }

        @media (max-width: 768px) {
            .container {
                padding: 20px;
            }

            h1 {
                font-size: 2rem;
            }

            h2 {
                font-size: 1.5rem;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        ${content}

        <div class="footer">
            <p>Generated by Forkyy AI Templates • Powered by OpenManus</p>
        </div>
    </div>
</body>
</html>`
}
