/**
 * Format content as Markdown with enhanced formatting
 */
export function formatAsMarkdown(
  content: string,
  metadata?: {
    title?: string
    author?: string
    date?: string
    template?: string
  }
): string {
  let formatted = ''

  // Add frontmatter if metadata provided
  if (metadata) {
    formatted += '---\n'
    if (metadata.title) formatted += `title: "${metadata.title}"\n`
    if (metadata.author) formatted += `author: "${metadata.author}"\n`
    if (metadata.date) formatted += `date: "${metadata.date}"\n`
    if (metadata.template) formatted += `template: "${metadata.template}"\n`
    formatted += '---\n\n'
  }

  // Add the main content
  formatted += content

  // Add footer
  formatted += '\n\n---\n\n'
  formatted += '*Generated by Forkyy AI Templates • Powered by OpenManus*\n'

  return formatted
}

/**
 * Convert content to GitHub-flavored Markdown
 */
export function toGitHubMarkdown(content: string): string {
  // Ensure proper spacing around headers
  content = content.replace(/^(#{1,6})\s/gm, '\n$1 ')

  // Ensure code blocks have language identifiers when possible
  content = content.replace(/```\n/g, '```plaintext\n')

  return content
}
